# B4: DFGS-T identity sampling plus cross-camera within-ID sampling with P4K2
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0
  I2T_WEIGHT: 1.0
  T2I_WEIGHT: 1.0
  VIFI_WEIGHT : 'pretrained/vifi/vifi_clip_k400_for_vsla.pth'
  USE_VIFI_WEIGHT : True
  PROMPT_LEN : 8 
  USE_LEARNABLE_PROMPT : True
  PBP_CAMERA: True
  PBP_VIEW: False
  PBP_PROMPT_DEEP: 3
  PBP_PROMPT_LEN: 16
  USE_ADAPTER: True
  ADAPTER_TYPE: 'dat_and_cross'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  SAMPLER: 'dfgs_cross_camera'
  NUM_INSTANCE: 2
  NUM_WORKERS: 8
  SEQ_LEN: 8
  PID_SAMPLES_PER_EPOCH: 4
  DFGS_GRAPH: 'configs/adapter/innovation/g2a_dfgs_text_graph_m2_k10.json'
  DFGS_PROBABILITY: 1.0

SOLVER:
  SEED: 2025
  STAGE1:
    IMS_PER_BATCH: 32
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 10
    WARMUP_EPOCHS: 5

  STAGE2:
    IMS_PER_BATCH: 8
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.0002
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.00025
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    EVAL_PERIOD: 10
    BIAS_LR_FACTOR: 2

    STEPS: [60, 90]
    GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 4
  RE_RANKING: False
  WEIGHT: 'output/ablation/B4_crosscam_dfgs_p4k2_seed2025_lr2e4/ViT-B-16_mAP_best.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  ALL_FRAMES: False
  DISTANCE: 'cosine'

DATASETS:
  NAMES: ('g2a')
  ROOT_DIR: ('../G2A-VReID')
OUTPUT_DIR: 'output/innovation/B4_crosscam_dfgs_p4k2_seed2025_lr2e4'
